const Map<String, String> en = {
  "name_app": "MyApp",
  "error_wrong": "Something went wrong try again later",
  "name": "Name",
  "pin": "PIN",
  "trial_period_end": "Your trial period will end on %s",
  "oops": "Oops!",
  "password": "Password",
  "required_field": "field is required",
  "forgot_password": "Forgot Password",
  "error_login": "name or password is incorrect",
  "error_server": "error connecting to server please try again",
  "success_login": "login successful",
  "completed_success": "Completed successfully",
  "signin": "Sign in",
  "signup": "Sign up",
  "contacts": "Contacts",
  "profile": "Profile",
  "logout": "Logout",
  "exit_app": "Are you sure you want to Exit?",
  "get_started": "Get Started",
  "no": "No",
  "yes": "Yes",
  "error_connection": "No internet connection. Make sure Wi-Fi or cellular data is turned on, then try again",
  "no_account": "No account yet?",
  "sign_up": "Sign Up",
  "sign_in": "Sign In",
  "rest": "Reset",
  "try_again": "Try Again",
  "welcome": "Bienvenue",
  "login": "Se connecter",
  "username": "Username",
  "access": "Acceder",
  "forgot_pass": "mot de passe oublié?",
  "remember_me": "Se souvenir de moi",
  "already_have_account": "Vous avez déjà un compte?",
  "dont_have_account": "Vous n'avez pas encore de compte?",
  "new_user": "Nouveau utilisateur?",
  "create_your_account": "Créer votre compte",
  "email_invalid": "Invalid email address",
  "phone_invalid": "Invalid phone number",
  "enter_your_email": "insérer un E-mail où nous pouvons vous envoyer un code de récupération",
  "send": "Envoyer",
  "first_name": "Votre nom",
  "last_name": "Votre prenom",
  "phone": "N° telephone",
  "reaper_password": "Retaper Password",
  "create_account": "Création de compte",
  "validate": "Valider",
  "email": "Email",
  "email_fr": "E-mail",
  "track_shipment": "Suivre une expédition sans se connecter",
  "shipping_no": "N d'expédition",
  "recover_password": "Récupération de votre mot de passe",
  "next": "Suivant",
  "you_are": "Vous êtes",
  "charger": "Chargeur",
  "carrier": "Transporteur",
  "your_company": "Nom de votre entreprise",
  "address": "Adresse",
  "city": "Ville",
  "ice": "ICE",
  "passwords_not_match": "Passwords ne correspondent pas",

};
